import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  dubaiBar: {
    width: 65,
    height: 65,
    borderRadius: 40,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#55A7ED',
    position: 'absolute',
    top: 15,
    left: 25,
  },
  dubai: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  dubaiText: {
    position: 'absolute',
    top: 85,
    left: 43,
    fontWeight:'bold',
    fontSize: 11,
    color: '#212121',
  },
  maldivesBar: {
    width: 65,
    height: 65,
    borderRadius: 40,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#55A7ED',
    position: 'absolute',
    top: 15,
    left: 100,
  },
  maldives: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  maldivesText: {
    position: 'absolute',
    top: 85,
    left: 109,
    fontSize: 11,
    fontWeight:'bold',
    color: '#212121',
  },
  baliBar: {
    width: 65,
    height: 65,
    borderRadius: 40,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#55A7ED',
    position: 'absolute',
    top: 15,
    left: 175,
  },
  bali: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  baliText: {
    position: 'absolute',
    fontWeight:'bold',
    top: 85,
    left: 198,
    fontSize: 11,
    color: '#212121',
  },
  veniceBar: {
    width: 65,
    height: 65,
    borderRadius: 40,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#55A7ED',
    position: 'absolute',
    top: 15,
    left: 250,
  },
  venice: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  veniceText: {
    position: 'absolute',
    top: 85,
    right: 86,
    fontWeight:'bold',
    fontSize: 11,
    color: '#212121',
  },
  londonBar: {
    width: 65,
    height: 65,
    borderRadius: 40,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#55A7ED',
    position: 'absolute',
    top: 15,
    left: 325,
  },
  london: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  londonText: {
    position: 'absolute',
    top: 85,
    right: 8,
    fontWeight:'bold',
    fontSize: 11,
    color: '#212121',
  },
  threePoints: {
    position: 'absolute',
    top: 100,
    left: 185
  },
  recommended: {
    color: '#212121',
    fontWeight: 'bold',
    position: 'absolute',
    top: 125,
    left: 22,
  },
  viewAllR: {
    fontSize: 10,
    position: 'absolute',
    color:'#D0D0D0',
    top: 125,
    right: 22,
  },
  recommendedMid: {
    overflow: 'hidden',
    width:'45%',
    height:'27%',
    borderRadius: 20,
    position: 'absolute',
    justifyContent:'center',
    top: 152,
    left: 107,
  },
  recommendedMidImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  recommendedLeft: {
    overflow: 'hidden',
    width:'43%',
    height:'20%',
    borderRadius: 20,
    position: 'absolute',
    top: 175,
    left: -85,
  },
  recommendedLeftImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  recommendedRight: {
    overflow: 'hidden',
    width:'43%',
    height:'20%',
    borderRadius: 20,
    position: 'absolute',
    top: 175,
    right: -85,
  },
  recommendedRightImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  popular: {
    color: '#212121',
    fontWeight: 'bold',
    position: 'absolute',
    bottom:365,
    left: 22,
  },
  viewAllP: {
    fontSize: 10,
    position: 'absolute',
    color:'#D0D0D0',
    bottom:365,
    right: 22,
  },
  pd1:{
    position:'absolute',
    overflow:'hidden',
    bottom:250,
    width:'90%',
    left:20,
    height:100,
    borderRadius:10,
    backgroundColor:'white',
    shadowColor: '#000',
    shadowOffset: {width: 2, height: 2},
    shadowRadius: 4,
    elevation: 5,
  },
  pdImageBar:{
    width:'30%',
    height:'100%',
    borderRadius:10,
    overflow:'hidden',
  },
  pdImage:{
    width:'100%',
    height:'100%',
    resizeMode:'cover',
  },
  enjoy1:{
    fontSize:15,
    position:'absolute',
    top:12,
    left:125,
    color:'#212121',
  },
  enjoy2:{
    fontSize:15,
    position:'absolute',
    top:32,
    left:125,
    color:'#212121',
  },
  location:{
    fontSize:10,
    position:'absolute',
    bottom:20,
    left:135,
    color:'#D0D0D0',
  },
  locationImage:{
    width:10,
    height:10,
    position:'absolute',
    bottom:22,
    left:122
  },
  from:{
    fontSize:10,
    color:'#212121',
    position:'absolute',
    top:15,
    right:17,
    fontWeight:'bold'
  },
  price:{
    fontSize:11,
    color:'#cd9f7c',
    position:'absolute',
    top:40,
    right:12,
    fontWeight:'bold'
  },
  perPerson:{
    fontSize:10,
    color:'#212121',
    position:'absolute',
    top:60,
    right:12,
  },
  pd2:{
    position:'absolute',
    overflow:'hidden',
    bottom:130,
    width:'90%',
    left:20,
    height:100,
    borderRadius:10,
    backgroundColor:'white',
    shadowColor: '#000',
    shadowOffset: {width: 2, height: 2},
    shadowRadius: 4,
    elevation: 5,
  },
  pd3:{
    position:'absolute',
    overflow:'hidden',
    bottom:20,
    width:'90%',
    left:20,
    height:100,
    borderRadius:10,
    backgroundColor:'white',
    shadowColor: '#000',
    shadowOffset: {width: 2, height: 2},
    shadowRadius: 4,
    elevation: 5,
  },
  heartBar:{
    backgroundColor:'rgba(0,0,0,0.2)',
    width:25,
    height:25,
    borderRadius:25,
    position:'absolute',
    overflow:'hidden',
    right:10,
    top:10
  },
  heart:{
    width:15,
    height:15,
    top:6,
    left:5
  },
  locationWhiteImage:{
    position:'absolute',
    bottom:10,
    left:10,
    width:13,
    height:13
  },
  locationWhiteText:{
    color:'#FFFFFF',
    fontSize:10,
    position:'absolute',
    bottom:10,
    left:25
  },
  star:{
    width:13,
    height:13,
    position:'absolute',
    bottom:10,
    right:25,
  },
  score:{
    position:'absolute',
    bottom:10,
    right:10,
    color:'#FFFFFF',
    fontSize:9,
    fontWeight:'bold',
  },
  starPD:{
    position:'absolute',
    top:3,
    right:20,
    width:13,
    height:13
  },
  scorePD:{
    position:'absolute',
    top:3,
    right:5,
    color:'#FFFFFF',
    fontSize:9,
    fontWeight:'bold',
  }
});
