import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    height: '70%',
    widht: '100%',
    flexDirection: 'row',
  },
  panel: {
    position: 'absolute',
    bottom: 0,
    height: '60%',
    width: '100%',
    backgroundColor: 'white',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchBar: {
    top: -25,
    position: 'absolute',
    borderRadius: 15,
    backgroundColor: 'white',
    height: 60,
    width: '90%',
    shadowColor: '#000',
    shadowOffset: {width: 2, height: 2},
    shadowRadius: 4,
    elevation: 5,
    flexDirection: 'row',
  },
  searchBarText: {
    marginTop: 18,
    marginLeft: 10,
    fontSize: 17,
    fontWeight: '400',
    fontFamily: 'Helvetica Neue',
    left: 10,
    color: 'rgba(0,0,0,0.1)',
  },
  menu: {
    backgroundColor: 'white',
    width: 45,
    height: 45,
    top: 20,
    left: 25,
    borderRadius: 8,
  },
  notifications: {
    position:'absolute',
    right: 110,
    top: 25,
    width:10,
    height:10
  },
  profileBar: {
    width: 50,
    height: 50,
    borderRadius: 40,
    top: 15,
    overflow: 'hidden',
    position:'absolute',
    right: 22,
    borderWidth: 2,
    borderColor: '#55A7ED',
  },
  profile: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  helloText: {
    fontSize: 30,
    color: '#FBFFFD',
    fontWeight: 'bold',
    position:'absolute',
    top: 100,
    left: -20,
  },
  whereText: {
    fontSize: 15,
    color: '#FBFFFD',
    fontWeight: '500',
    top: 140,
    left: -20
  },
  flightBar:{
    width:73,
    height:85,
    backgroundColor:'rgba(255,255,255,0.4)',
    position:'absolute',
    top:175,
    left:30,
    borderRadius:15,
    borderWidth: 2,
    borderColor: '#55A7ED',
  },
  flight: {
    width:45,
    height:45,
    left:14,
    top:14
  },
  flightText:{
    color: '#FBFFFD',
    fontWeight: 'bold',
    fontSize:12,
    position:'absolute',
    top:60,
    left:20
  },
  hotelBar:{
    width:73,
    height:85,
    backgroundColor:'rgba(255,255,255,0.4)',
    position:'absolute',
    top:175,
    left:114,
    borderRadius:15,
    borderWidth: 2,
    borderColor: '#55A7ED',
  },
  hotelText:{
    color: '#FBFFFD',
    fontWeight: 'bold',
    fontSize:12,
    position:'absolute',
    top:60,
    left:20
  },
  hotel: {
    width:40,
    height:40,
    left:16.5,
    top:16.5
  },
  holidayBar:{
    width:73,
    height:85,
    backgroundColor:'rgba(255,255,255,0.4)',
    position:'absolute',
    top:175,
    right:114,
    borderRadius:15,
    borderWidth: 2,
    borderColor: '#55A7ED',
  },
  holidayText:{
    color: '#FBFFFD',
    fontWeight: 'bold',
    fontSize:12,
    position:'absolute',
    top:60,
    left:16,
  },
  holiday: {
    width:40,
    height:40,
    left:16.5,
    top:16.5
  },
  offersBar:{
    backgroundColor:'rgba(255,255,255,0.4)',
    width:73,
    height:85,
    position:'absolute',
    top:175,
    right:30,
    borderRadius:15,
    borderWidth: 2,
    borderColor: '#55A7ED',
  },
  offersText:{
    color: '#FBFFFD',
    fontWeight: 'bold',
    fontSize:12,
    position:'absolute',
    top:60,
    left:19
  },
  offers: {
    width:40,
    height:40,
    left:16.5,
    top:16.5
  },
  dubaiBar:{
    width: 65,
    height: 65,
    borderRadius: 40,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#55A7ED',
    position:'absolute',
    top:45,
    left:25
  },
  dubai:{
    width: '100%',
    height: '100%',
    resizeMode: 'cover',  
  },
  dubaiText:{
    position:'absolute',
    top:-115,
    left:-152,
    fontWeight:'bold',
    fontSize:11,
    color:'#212121',
  },
  maldivesBar:{
    width: 65,
    height: 65,
    borderRadius: 40,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#55A7ED',
    position:'absolute',
    top:45,
    left:100
  },
  maldives:{
    width: '100%',
    height: '100%',
    resizeMode: 'cover',  
  },
  maldivesText:{
    position:'absolute',
    top:-115,
    fontWeight:'bold',
    left:-85,
    fontSize:11,
    color:'#212121',
  },
  baliBar:{
    width: 65,
    height: 65,
    borderRadius: 40,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#55A7ED',
    position:'absolute',
    top:45,
    left:175
  },
  bali:{
    width: '100%',
    height: '100%',
    resizeMode: 'cover',  
  },
  baliText:{
    position:'absolute',
    top:-115,
    left:4,
    fontWeight:'bold',
    fontSize:11,
    color:'#212121',
  },
  veniceBar:{
    width: 65,
    height: 65,
    borderRadius: 40,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#55A7ED',
    position:'absolute',
    top:45,
    left:250
  },
  venice:{
    width: '100%',
    height: '100%',
    resizeMode: 'cover',  
  },
  veniceText:{
    position:'absolute',
    top:-115,
    right:-105,
    fontWeight:'bold',
    fontSize:11,
    color:'#212121',
  },
  londonBar:{
    width: 65,
    height: 65,
    borderRadius: 40,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#55A7ED',
    position:'absolute',
    top:45,
    left:325
  },
  london:{
    width: '100%',
    height: '100%',
    resizeMode: 'cover',  
  },
  londonText:{
    position:'absolute',
    top:-115,
    right:-183,
    fontWeight:'bold',
    fontSize:11,
    color:'#212121',
  },
  threePoints:{
    position:'absolute',
    top:125
  },
  recommended:{
    color:'#212121',
    fontWeight:'bold',
    left:22
  },
  viewAllR:{
    fontSize:10,
    color:'#D0D0D0',
    right:20
  },
  containerRecommend:{
    flexDirection:'row',
    justifyContent:'space-between',
    position:'absolute',
    top:150,
    width:'100%',
  },
  recommendedMid:{
    overflow: 'hidden',
    width:'45%',
    height:'25%',
    borderRadius: 20,
    position:'absolute',
    bottom:85,
    alignSelf:'center',
  },
  recommendedMidImage:{
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  recommendedLeft:{
    overflow: 'hidden',
    width:'43%',
    height:'20%',
    borderRadius: 20,
    position:'absolute',
    bottom:107,
    left:-85,
  },
  recommendedLeftImage:{
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  recommendedRight:{
    overflow: 'hidden',
    width:'43%',
    height:'20%',
    borderRadius: 20,
    position:'absolute',
    bottom:107,
    right:-85,
  },
  recommendedRightImage:{
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  popular:{
    color:'#212121',
    fontWeight:'bold',
    marginRight:200
  },
  viewAllP:{
    fontSize:10,
    color:'#D0D0D0',
    right:22
  },
  containerPopular:{
    flexDirection:'row',
    justifyContent:'center',
    position:'absolute',
    bottom:40,
    left:22,
  },
  heartBar:{
    backgroundColor:'rgba(0,0,0,0.2)',
    width:25,
    height:25,
    borderRadius:25,
    position:'absolute',
    overflow:'hidden',
    right:10,
    top:10
  },
  heart:{
    width:15,
    height:15,
    top:6,
    left:5
  },
  locationWhiteImage:{
    position:'absolute',
    bottom:10,
    left:10,
    width:13,
    height:13
  },
  locationWhiteText:{
    color:'#FFFFFF',
    fontSize:10,
    position:'absolute',
    bottom:10,
    left:25
  },
  star:{
    width:13,
    height:13,
    position:'absolute',
    bottom:10,
    right:25,
  },
  score:{
    position:'absolute',
    bottom:10,
    right:10,
    color:'#FFFFFF',
    fontSize:9,
    fontWeight:'bold',
  },
  pd1:{
    position:'absolute',
    overflow:'hidden',
    bottom:-70,
    width:'90%',
    left:20,
    height:100,
    borderRadius:10,
    backgroundColor:'white',
    shadowColor: '#000',
    shadowOffset: {width: 2, height: 2},
    shadowRadius: 4,
    elevation: 5,
  },
  pdImageBar:{
    width:'30%',
    height:'100%',
    borderRadius:10,
    overflow:'hidden',
  },
  pdImage:{
    width:'100%',
    height:'100%',
    resizeMode:'cover',
  },
  enjoy1:{
    fontSize:15,
    position:'absolute',
    top:12,
    left:125,
    color:'#212121',
  },
  enjoy2:{
    fontSize:15,
    position:'absolute',
    top:32,
    left:125,
    color:'#212121',
  },
  location:{
    fontSize:10,
    position:'absolute',
    bottom:20,
    left:135
  },
  locationImage:{
    width:10,
    height:10,
    position:'absolute',
    bottom:22,
    left:122
  },
  from:{
    fontSize:10,
    color:'#212121',
    position:'absolute',
    top:15,
    right:17,
    fontWeight:'bold'
  },
  price:{
    fontSize:11,
    color:'#cd9f7c',
    position:'absolute',
    top:40,
    right:12,
    fontWeight:'bold'
  },
  perPerson:{
    fontSize:10,
    color:'#212121',
    position:'absolute',
    top:60,
    right:12,
  },
  starPD:{
    position:'absolute',
    top:3,
    right:20,
    width:13,
    height:13
  },
  scorePD:{
    position:'absolute',
    top:3,
    right:5,
    color:'#FFFFFF',
    fontSize:9,
    fontWeight:'bold',
  }
});
