import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  threeLine: {
    position: 'absolute',
    top: 20,
    left: 20,
  },
  booking: {
    fontSize: 22,
    color: '#212121',
    textAlign: 'center',
    top: 22,
    fontWeight: 'bold',
  },
  searchBlack: {
    position: 'absolute',
    top: -5,
    right: 20,
    width: 25,
    height: 25,
  },
  ongoingBar: {
    borderWidth: 1,
    borderColor: '#55A7ED',
    width: 100,
    height: 25,
    position: 'absolute',
    top: 100,
    left: 30,
    borderRadius: 20,
  },
  ongoingText: {
    textAlign: 'center',
    top: 2,
    color: '#55A7ED',
    fontSize: 12,
  },
  completedBar: {
    backgroundColor: '#55A7ED',
    width: 100,
    height: 25,
    position: 'absolute',
    top: 100,
    left: 141,
    borderRadius: 20,
  },
  completedText: {
    textAlign: 'center',
    top: 2.5,
    color: '#FFFFFF',
    fontSize: 12,
  },
  cancelledBar: {
    borderWidth: 1,
    borderColor: '#55A7ED',
    width: 100,
    height: 25,
    position: 'absolute',
    top: 100,
    right: 30,
    borderRadius: 20,
  },
  cancelledText: {
    textAlign: 'center',
    top: 2.5,
    color: '#55A7ED',
    fontSize: 12,
  },
  //-----------------------------------------
  book1: {
    width: '90%',
    height: 200,
    borderRadius: 10,
    top: 100,
    shadowColor: '#000',
    shadowOffset: {width: 2, height: 2},
    shadowRadius: 4,
    elevation: 5,
    overflow: 'hidden',
  },
  hotelRoomImage: {
    width: 75,
    height: 75,
    borderRadius: 10,
    top: 30,
    left: 20,
  },
  hotelName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#212121',
    position: 'absolute',
    top: 40,
    left: 110,
  },
  location: {
    position: 'absolute',
    top: 62,
    left: 110,
    fontSize: 11,
    color: 'grey',
  },
  paidBar: {
    backgroundColor: '#D3E7FD',
    width: 60,
    height: 20,
    position: 'absolute',
    top: 85,
    left: 110,
    borderRadius: 5,
  },
  paidText: {
    color: '#212121',
    textAlign: 'center',
    marginTop: 3,
    fontSize: 10,
  },
  line: {
    height: 1,
    width: '85%',
    backgroundColor: '#D3E7FD',
    top: 50,
    left: 26,
  },
  cancelBookingBar: {
    borderWidth: 1,
    borderColor: '#55A7ED',
    width: 120,
    height: 30,
    position: 'absolute',
    top: 145,
    left: 45,
    borderRadius: 20,
  },
  cancelBookingText: {
    textAlign: 'center',
    color: '#55A7ED',
    fontSize: 10,
    fontWeight: 'bold',
    top: 5,
  },
  viewTicketBar: {
    backgroundColor: '#55A7ED',
    width: 120,
    height: 30,
    position: 'absolute',
    top: 145,
    right: 45,
    borderRadius: 20,
  },
  viewTicketText: {
    textAlign: 'center',
    top: 7,
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  //-----------------------------------------

  book1: {
    width: '90%',
    height: 200,
    margin: 20,
    borderRadius: 10,
    top: 100,
    shadowColor: '#000',
    shadowOffset: {width: 2, height: 2},
    shadowRadius: 4,
    elevation: 5,
    overflow: 'hidden',
  },
  hotelRoomImage: {
    width: 75,
    height: 75,
    borderRadius: 10,
    top: 30,
    left: 20,
  },
  hotelName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#212121',
    position: 'absolute',
    top: 40,
    left: 110,
  },
  location: {
    position: 'absolute',
    top: 62,
    left: 110,
    fontSize: 11,
    color: 'grey',
  },
  paidBar: {
    backgroundColor: '#D3E7FD',
    width: 60,
    height: 20,
    position: 'absolute',
    top: 85,
    left: 110,
    borderRadius: 5,
  },
  paidText: {
    color: '#212121',
    textAlign: 'center',
    marginTop: 3,
    fontSize: 10,
  },
  line: {
    height: 1,
    width: '85%',
    backgroundColor: '#D3E7FD',
    top: 50,
    left: 26,
  },
  cancelBookingBar: {
    borderWidth: 1,
    borderColor: '#55A7ED',
    width: 120,
    height: 30,
    position: 'absolute',
    top: 145,
    left: 45,
    borderRadius: 20,
  },
  cancelBookingText: {
    textAlign: 'center',
    color: '#55A7ED',
    fontSize: 10,
    fontWeight: 'bold',
    top: 5,
  },
  viewTicketBar: {
    backgroundColor: '#55A7ED',
    width: 120,
    height: 30,
    position: 'absolute',
    top: 145,
    right: 45,
    borderRadius: 20,
  },
  viewTicketText: {
    textAlign: 'center',
    top: 7,
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  //-----------------------------------------
  book2:{
    width:'90%',
    height: 200,
    margin:20,
    borderRadius:10,
    top:60,
    shadowColor: '#000',
    shadowOffset: {width: 2, height: 2},
    shadowRadius: 4,
    elevation:5,
    overflow:'hidden',
  },
  book3:{
    width:'90%',
    height: 200,
    margin:20,
    borderRadius:10,
    top:20,
    shadowColor: '#000',
    shadowOffset: {width: 2, height: 2},
    shadowRadius: 4,
    elevation:5,
    overflow:'hidden',
  },
  bottomBar:{
    height:'20%',
    width:'100%',
    backgroundColor:'white',
    bottom:75,
    flexDirection:'row',
    borderWidth:0.5,
    borderColor:'black'
  },
  home:{
    position:'absolute',
    left:55,
    top:15
  },
  homeText:{
    color:'black',
    position:'absolute',
    top:50,
    left:55,
    fontSize:12
  },
  profileM:{
    position:'absolute',
    right:55,
    top:15
  },
  profileMText:{
    color:'black',
    position:'absolute',
    top:50,
    right:54,
    fontSize:12
  },
  bookingImage:{
    position:'absolute',
    top:15,
    left:135
  },
  bookingText:{
    color:'black',
    top:50,
    left:130,
    fontSize:12
  },
  locationWhiteM:{
    position:'absolute',
    right:135,
    top:15
  },
  locationWhiteText:{
    color:'black',
    top:50,
    left:167,
    fontSize:12
  }


});
